### ISSUE TITLE
Question: Why do Juniper and Diesel schemas have to be separated?

### ISSUE THREAD

**Issue by jackHedaya** [pleshevskiy/rust-juniper-graphql-diesel-rocket-example#3]
Hey!

I'm using your project as a template for mine and am a little confused regarding the duplicate schemas for Juniper and Diesel. I'm  still learning Rust so there may be an ecosystem requirement I'm not understanding. Thanks!

Jack

**Comment by pleshevskiy** [comment]
Sorry for delay.

Regardless of which language you use, it is always best to divide it into 3 layers. Repository (Diesel), business logic and output (Juniper). This example is a bit dirty and omits the business logic. If you have this separation, your project will be easy to maintain.
